In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('../data/newst_data.csv')

In [3]:
data["query"] = data["query"].astype("category")
data["w_doclen"] = data["w_doclen"].astype("int")
data["section"] = data["section"].astype("category")
data["name"] = data["name"].astype("category")
data["section"] = data["section"].cat.codes
#data["relevance"] = data["relevance"].astype("int")
#data.relevance[data.relevance <= 1] = 0
#data.relevance[data.relevance == 2] = 1
#data.relevance[data.relevance >= 2] = 1
data["rank"] = data["rank"].astype("category")


In [4]:
data.describe()

section     indegree    outdegree       w_name  w_name_desc  \
count  2448.000000  2448.000000  2448.000000  2448.000000  2448.000000   
mean      3.996324    13.892157    13.503676     0.608854     0.591422   
std       3.173821    33.927249    36.235223     0.205312     0.152930   
min       0.000000     0.000000     0.000000     0.500000     0.500000   
25%       2.000000     1.000000     0.000000     0.500000     0.500000   
50%       4.000000     4.000000     5.000000     0.500000     0.500000   
75%       8.000000    13.000000    11.000000     0.500000     0.646715   
max      10.000000   394.000000   355.000000     1.000000     1.000000   

            w_desc        w_lib  w_return_vals        w_env      w_files  \
count  2448.000000  2448.000000    2448.000000  2448.000000  2448.000000   
mean      0.503225     0.503276       0.511072     0.503371     0.515782   
std       0.012224     0.038461       0.056123     0.030938     0.070103   
min       0.500000     0.500000       0.500000     0.500000     0.500000   
25%       0.500314     0.500000       0.500000     0.500000     0.500000   
50%       0.500943     0.500000       0.500000     0.500000     0.500000   
75%       0.502740     0.500000       0.500000     0.500000     0.500000   
max       0.938770     0.999980       1.000000     0.995826     1.000000   

       w_exit_status  w_diagnostics     w_errors  w_special_keywords  \
count    2448.000000    2448.000000  2448.000000         2448.000000   
mean        0.508199       0.502594     0.504132            0.514202   
std         0.056711       0.025998     0.028089            0.055809   
min         0.500000       0.500000     0.500000            0.500000   
25%         0.500000       0.500000     0.500000            0.500000   
50%         0.500000       0.500000     0.500000            0.500000   
75%         0.500000       0.500000     0.500000            0.503043   
max         1.000000       0.998989     0.910067            0.998759   

       w_xr_context    w_machine       w_doclen      w_total  
count   2448.000000  2448.000000    2448.000000  2448.000000  
mean       0.506785     0.500204    2524.439134     0.627022  
std        0.035020     0.010106    8786.578076     0.005660  
min        0.500000     0.500000      22.000000     0.622459  
25%        0.500000     0.500000     228.750000     0.622504  
50%        0.500000     0.500000     589.500000     0.624363  
75%        0.500000     0.500000    1754.250000     0.630819  
max        0.989540     1.000000  113084.000000     0.660942

In [5]:
print(data.columns)

Index(['query', 'name', 'section', 'rank', 'indegree', 'outdegree', 'w_name',
       'w_name_desc', 'w_desc', 'w_lib', 'w_return_vals', 'w_env', 'w_files',
       'w_exit_status', 'w_diagnostics', 'w_errors', 'w_special_keywords',
       'w_xr_context', 'w_machine', 'w_doclen', 'w_total'],
      dtype='object')


In [6]:
data = data.drop(labels=['w_machine'], axis=1)

In [7]:
# Set w_total = 0.68 for rank = 4, 0.60 for rank = 0, 0.62 for rank = 1, 0.64 for rank =2, 0.66 for rank = 3
data.loc[data['rank'] == 4, 'w_total'] = 0.67
#data.loc[data['rank'] == 3, 'w_total'] = 1.0
#data.loc[data['rank'] == 2, 'w_total'] = 0.50
#data.loc[data['rank'] == 1, 'w_total'] = 0.10
data.loc[data['rank'] == 0, 'w_total'] = 0.62

In [8]:
data.describe()

section     indegree    outdegree       w_name  w_name_desc  \
count  2448.000000  2448.000000  2448.000000  2448.000000  2448.000000   
mean      3.996324    13.892157    13.503676     0.608854     0.591422   
std       3.173821    33.927249    36.235223     0.205312     0.152930   
min       0.000000     0.000000     0.000000     0.500000     0.500000   
25%       2.000000     1.000000     0.000000     0.500000     0.500000   
50%       4.000000     4.000000     5.000000     0.500000     0.500000   
75%       8.000000    13.000000    11.000000     0.500000     0.646715   
max      10.000000   394.000000   355.000000     1.000000     1.000000   

            w_desc        w_lib  w_return_vals        w_env      w_files  \
count  2448.000000  2448.000000    2448.000000  2448.000000  2448.000000   
mean      0.503225     0.503276       0.511072     0.503371     0.515782   
std       0.012224     0.038461       0.056123     0.030938     0.070103   
min       0.500000     0.500000       0.500000     0.500000     0.500000   
25%       0.500314     0.500000       0.500000     0.500000     0.500000   
50%       0.500943     0.500000       0.500000     0.500000     0.500000   
75%       0.502740     0.500000       0.500000     0.500000     0.500000   
max       0.938770     0.999980       1.000000     0.995826     1.000000   

       w_exit_status  w_diagnostics     w_errors  w_special_keywords  \
count    2448.000000    2448.000000  2448.000000         2448.000000   
mean        0.508199       0.502594     0.504132            0.514202   
std         0.056711       0.025998     0.028089            0.055809   
min         0.500000       0.500000     0.500000            0.500000   
25%         0.500000       0.500000     0.500000            0.500000   
50%         0.500000       0.500000     0.500000            0.500000   
75%         0.500000       0.500000     0.500000            0.503043   
max         1.000000       0.998989     0.910067            0.998759   

       w_xr_context       w_doclen      w_total  
count   2448.000000    2448.000000  2448.000000  
mean       0.506785    2524.439134     0.635860  
std        0.035020    8786.578076     0.019970  
min        0.500000      22.000000     0.620000  
25%        0.500000     228.750000     0.622484  
50%        0.500000     589.500000     0.623969  
75%        0.500000    1754.250000     0.646423  
max        0.989540  113084.000000     0.670000

In [9]:
X = data.ix[:, 6:-4]


In [10]:
X.columns

Index(['w_name', 'w_name_desc', 'w_desc', 'w_lib', 'w_return_vals', 'w_env',
       'w_files', 'w_exit_status', 'w_diagnostics', 'w_errors'],
      dtype='object')

In [11]:
y = data.ix[:, -1:]

In [12]:
seed = 42

In [13]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values.ravel(), test_size=0.20, random_state=seed)
X_train, X_val,y_train, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=seed)

/home/abhinav/miniconda3/envs/cadl/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [788]:
from sklearn.preprocessing import StandardScaler
stdscaler = StandardScaler()
stdscaler.fit(X_train)
X_train= stdscaler.transform(X_train)
X_val = stdscaler.transform(X_val)
X_test= stdscaler.transform(X_test)


In [14]:
from sklearn.metrics import mean_squared_error
def mse(model, X_test, y_test):
    y_true, y_pred = y_test, model.predict(X_test)
    return (mean_squared_error(y_true, y_pred))


In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

In [16]:
lm = LinearRegression(normalize=False)
lm.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
print(mse(lm, X_train, y_train))
print(mse(lm, X_val, y_val))

0.000171808278601
0.00018307396181


In [18]:
mse(lm, X_test, y_test)

0.00019371474334001158

In [19]:
print(lm.coef_)

[ 0.06821901  0.02468532  0.04045685  0.00356061  0.02982234  0.00012415
 -0.01107191  0.02385655  0.03359916  0.02360978]


In [20]:
lm.intercept_

0.50677693419413294

In [21]:
ridge = Ridge(alpha=1, tol=1e-1)
ridge.fit(X_train, y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.1)

In [22]:
print(ridge.score(X_train, y_train))
print(ridge.score(X_val, y_val))
print(mse(ridge, X_train, y_train))
print(mse(ridge, X_val, y_val))

0.550292287481
0.565272359725
0.000172427032008
0.000183566412536


In [23]:
ridge.score(X_test, y_test)

0.55058985660920179

In [24]:
mse(ridge, X_test, y_test)

0.00019054113098838736

In [131]:
print(ridge.coef_)

[ 0.06794592  0.02396351  0.0105111   0.00257977  0.02572427  0.00151958
 -0.00928841  0.01873014  0.01856293  0.01610992]


In [132]:
ridge.intercept_

0.53735061082925895

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [133]:
rf = RandomForestRegressor(n_estimators=200, max_depth=15, max_features='auto', min_samples_split=2, n_jobs=1)

In [134]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=15,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=200, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [135]:
rf.score(X_train, y_train)

0.89918401787263236

In [136]:
rf.score(X_val, y_val)

0.60709705874503173

In [137]:
print (mse(rf, X_train, y_train))
print (mse(rf, X_val, y_val))

3.86548864814e-05
0.00016590567684


In [29]:
rf.score(X_test, y_test)

0.50092787788347737

In [832]:
rf.feature_importances_

array([ 0.54279857,  0.11843296,  0.09523817,  0.00132681,  0.01800907,
        0.00259071,  0.01351869,  0.0059429 ,  0.00760503,  0.01325691,
        0.05991658,  0.01521094,  0.10615265])

In [25]:
from sklearn.model_selection import GridSearchCV

In [28]:
rf = RandomForestRegressor()
params = {'n_estimators': [200, 300, 500, 600], 'max_depth': [15,18,20,25,30,50], 'max_features': [10, 'auto', 'sqrt', 'log2']}
gridsearch = GridSearchCV(rf, param_grid=params, scoring='neg_mean_squared_error', n_jobs=-1, cv=5)

In [29]:
f = gridsearch.fit(X_train, y_train)

In [30]:
f.best_estimator_.score(X_val, y_val)

0.62531806607922658

In [32]:
f.best_params_

{'max_depth': 15, 'max_features': 'sqrt', 'n_estimators': 300}

In [31]:
from sklearn.metrics import mean_squared_error
print("The model is trained on the full development set.")
print("The scores are computed on the full evaluation set.")
print()
y_true, y_pred = y_test, f.predict(X_test)
print(mean_squared_error(y_true, y_pred))
print()


The model is trained on the full development set.
The scores are computed on the full evaluation set.

0.000169345807336



In [61]:
f.best_estimator_.feature_importances_

array([ 0.51046613,  0.11883687,  0.16324559,  0.00215274,  0.05241182,
        0.0201753 ,  0.04246049,  0.02403219,  0.03068673,  0.03553214])

In [62]:
y_true, y_pred = y_test, f.best_estimator_.predict(X_test)
print(mean_squared_error(y_true, y_pred))
print(np.mean(((y_true - y_pred) ** 2)))

0.0477839829514
0.0477839829514


In [63]:
for i, j in zip(y_true, y_pred):
    print (i, j)

1.248182 0.622595145514
0.630652 0.672942454556
0.622776 0.633884122766
0.622463 0.643032274574
0.622463 0.633776089231
0.622503 0.63883051966
1.262254 1.25129989159
0.628163 0.661512887843
1.279624 1.14349649937
1.26165 1.22329946544
0.62249 0.63325192628
0.625116 0.731831267972
0.622494 0.638477865834
1.262468 1.20658377282
0.622487 0.634391828519
1.261712 1.24002096336
0.622471 0.625590828551
0.3128285 0.671998462041
0.626609 0.781534357578
1.247012 0.682981719601
0.635806 0.656924228987
0.622482 0.633197192582
1.253272 0.704682481274
1.263866 1.114184932
0.623264 0.622558742601
0.622472 0.625108016751
0.622462 0.603645968
0.3194235 1.24191783674
1.257468 0.741462827863
0.636061 0.881315604203
0.622784 0.643182619326
1.244998 0.639356758159
0.628751 0.745133873334
0.622534 0.638477865834
0.639131 1.01355084303
0.631216 1.24443388067
0.3137595 0.579433809297
0.622538 0.638262887008
0.622466 0.618526235243
0.622464 0.613744738781
1.276796 1.25267561669
0.631039 0.646264560348
0.623078

In [418]:
from sklearn.ensemble import GradientBoostingRegressor

In [419]:
gboost = GradientBoostingRegressor(n_estimators=560, max_depth=15,learning_rate=0.01, min_samples_split=6, max_features='log2')

In [420]:
gboost.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.01, loss='ls', max_depth=15,
             max_features='log2', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=6, min_weight_fraction_leaf=0.0,
             n_estimators=560, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [421]:
gboost.score(X_train, y_train)

0.99414205812276912

In [422]:
gboost.score(X_val, y_val)

0.65243157531987439

In [423]:
gboost.feature_importances_

array([  7.19848580e-02,   5.91980260e-02,   2.11569805e-01,
         8.53946169e-02,   2.30231487e-01,   1.67923816e-03,
         2.09102503e-02,   3.60059135e-03,   1.24457980e-02,
         8.94339138e-03,   1.05953829e-02,   1.36070968e-02,
         7.69400813e-02,   1.80496056e-02,   1.26072946e-05,
         1.74837164e-01])

In [313]:
from sklearn.neural_network import MLPRegressor

In [361]:
mlp = MLPRegressor(hidden_layer_sizes=(14,32,64,32,16,1), learning_rate='adaptive', activation='tanh', max_iter=1000,  solver='lbgfs', momentum=0.9)

In [362]:
mlp.fit(X_train, y_train)

MLPRegressor(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(14, 32, 64, 32, 16, 1),
       learning_rate='adaptive', learning_rate_init=0.001, max_iter=1000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='lbgfs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [363]:
mlp.score(X_train, y_train)

1.0898200191178375e-06

In [364]:
mlp.score(X_val, y_val)

-0.0088081326514710678