In [1]:
import seaborn as sns
import numpy as np
import sklearn
import pandas as pd
%matplotlib inline

In [49]:
data = pd.read_csv('../data/newst_data.csv')

In [50]:
data.columns

Index(['query', 'name', 'section', 'rank', 'indegree', 'outdegree', 'w_name',
       'w_name_desc', 'w_desc', 'w_lib', 'w_return_vals', 'w_env', 'w_files',
       'w_exit_status', 'w_diagnostics', 'w_errors', 'w_special_keywords',
       'w_xr_context', 'w_machine', 'w_doclen', 'w_total'],
      dtype='object')

In [51]:
data["query"] = data["query"].astype("category")
data["w_doclen"] = data["w_doclen"].astype("int")
data["section"] = data["section"].astype("category")
data["name"] = data["name"].astype("category")
data["section"] = data["section"].cat.codes
#data["rank"] = data["rank"].astype("int")
#data.rank[data.rank <= 1] = 0
#data.rank[data.relevance == 2] = 1
#data.rank[data.rank >= 2] = 1
#data.loc[data['rank'] <= 1, 'rank'] = 0
#data.loc[data['rank'] == 2, 'rank'] = 1
#data.loc[data['rank'] >= 2, 'rank'] = 2
data["rank"] = data["rank"].astype("category")


In [52]:
data.head()

query   name  section rank  indegree  outdegree  w_name  w_name_desc  \
0   abor   ftpd        8    4        27         43     0.5     0.500000   
1   abor    ftp        0    4        23         17     0.5     0.500000   
2  abort  kcopy        9    3         1          4     0.5     0.999945   
3  abort  abort        2    4        16          2     1.0     0.500000   
4  abort   wait        1    0        20          0     0.5     0.500000   

     w_desc  w_lib    ...     w_env  w_files  w_exit_status  w_diagnostics  \
0  0.500493    0.5    ...       0.5      0.5            0.5            0.5   
1  0.500375    0.5    ...       0.5      0.5            0.5            0.5   
2  0.501739    0.5    ...       0.5      0.5            0.5            0.5   
3  0.504899    0.5    ...       0.5      0.5            0.5            0.5   
4  0.500000    0.5    ...       0.5      0.5            0.5            0.5   

   w_errors  w_special_keywords  w_xr_context  w_machine  w_doclen   w_total  
0       0.5            0.501308      0.500000        0.5      3535  0.622490  
1       0.5            0.502630      0.500000        0.5      8336  0.622510  
2       0.5            0.500000      0.500000        0.5        74  0.630843  
3       0.5            0.806442      0.720238        0.5       147  0.647684  
4       0.5            0.500000      0.500000        0.5      1229  0.623353  

[5 rows x 21 columns]

In [53]:
data.describe()

section     indegree    outdegree       w_name  w_name_desc  \
count  2448.000000  2448.000000  2448.000000  2448.000000  2448.000000   
mean      3.996324    13.892157    13.503676     0.608854     0.591422   
std       3.173821    33.927249    36.235223     0.205312     0.152930   
min       0.000000     0.000000     0.000000     0.500000     0.500000   
25%       2.000000     1.000000     0.000000     0.500000     0.500000   
50%       4.000000     4.000000     5.000000     0.500000     0.500000   
75%       8.000000    13.000000    11.000000     0.500000     0.646715   
max      10.000000   394.000000   355.000000     1.000000     1.000000   

            w_desc        w_lib  w_return_vals        w_env      w_files  \
count  2448.000000  2448.000000    2448.000000  2448.000000  2448.000000   
mean      0.503225     0.503276       0.511072     0.503371     0.515782   
std       0.012224     0.038461       0.056123     0.030938     0.070103   
min       0.500000     0.500000       0.500000     0.500000     0.500000   
25%       0.500314     0.500000       0.500000     0.500000     0.500000   
50%       0.500943     0.500000       0.500000     0.500000     0.500000   
75%       0.502740     0.500000       0.500000     0.500000     0.500000   
max       0.938770     0.999980       1.000000     0.995826     1.000000   

       w_exit_status  w_diagnostics     w_errors  w_special_keywords  \
count    2448.000000    2448.000000  2448.000000         2448.000000   
mean        0.508199       0.502594     0.504132            0.514202   
std         0.056711       0.025998     0.028089            0.055809   
min         0.500000       0.500000     0.500000            0.500000   
25%         0.500000       0.500000     0.500000            0.500000   
50%         0.500000       0.500000     0.500000            0.500000   
75%         0.500000       0.500000     0.500000            0.503043   
max         1.000000       0.998989     0.910067            0.998759   

       w_xr_context    w_machine       w_doclen      w_total  
count   2448.000000  2448.000000    2448.000000  2448.000000  
mean       0.506785     0.500204    2524.439134     0.627022  
std        0.035020     0.010106    8786.578076     0.005660  
min        0.500000     0.500000      22.000000     0.622459  
25%        0.500000     0.500000     228.750000     0.622504  
50%        0.500000     0.500000     589.500000     0.624363  
75%        0.500000     0.500000    1754.250000     0.630819  
max        0.989540     1.000000  113084.000000     0.660942

In [54]:
data.columns

Index(['query', 'name', 'section', 'rank', 'indegree', 'outdegree', 'w_name',
       'w_name_desc', 'w_desc', 'w_lib', 'w_return_vals', 'w_env', 'w_files',
       'w_exit_status', 'w_diagnostics', 'w_errors', 'w_special_keywords',
       'w_xr_context', 'w_machine', 'w_doclen', 'w_total'],
      dtype='object')

In [55]:
X = data.ix[:, 6:-5]
y = data.ix[:, [3]]

In [56]:
X.columns

Index(['w_name', 'w_name_desc', 'w_desc', 'w_lib', 'w_return_vals', 'w_env',
       'w_files', 'w_exit_status', 'w_diagnostics', 'w_errors'],
      dtype='object')

In [57]:
y.columns

Index(['rank'], dtype='object')

In [58]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values.ravel(), test_size=0.20, random_state=43)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=43)

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
logistic_model = LogisticRegression(C=1.0, max_iter=500)

In [61]:
logistic_model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=500, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [62]:
logistic_model.score(X_train, y_train)

0.54469987228607919

In [63]:
logistic_model.score(X_val, y_val)

0.5714285714285714

In [64]:
logistic_model.score(X_test, y_test)

0.53061224489795922

In [17]:
print(logistic_model.coef_[0])

[ 3.7154569   1.85346932 -0.22117938 -0.24058422  0.73889749 -0.60951709
  0.78978051 -1.31374325 -0.3296918  -0.74217832]


In [18]:
logistic_model.intercept_

array([-0.91492825])

In [19]:
logistic_model.coef_?

In [69]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(X_train)
std_X_train = scalar.transform(X_train)
std__X_val = scalar.transform(X_val)
std_X_test = scalar.transform(X_test)

In [64]:
from sklearn.neural_network import MLPClassifier

In [65]:
mlp = MLPClassifier(hidden_layer_sizes=(16,32,64,32,16,8,2), solver='sgd', momentum=0.9, learning_rate='adaptive', max_iter=10000, verbose=True,activation='tanh')

In [66]:
mlp.fit(X_train, y_train)

Iteration 1, loss = 1.69209806
Iteration 2, loss = 1.64762693
Iteration 3, loss = 1.63059086
Iteration 4, loss = 1.61902613
Iteration 5, loss = 1.61429492
Iteration 6, loss = 1.61053517
Iteration 7, loss = 1.60697122
Iteration 8, loss = 1.60372353
Iteration 9, loss = 1.60067840
Iteration 10, loss = 1.59768400
Iteration 11, loss = 1.59466961
Iteration 12, loss = 1.59205000
Iteration 13, loss = 1.58898227
Iteration 14, loss = 1.58646557
Iteration 15, loss = 1.58383108
Iteration 16, loss = 1.58158413
Iteration 17, loss = 1.57922127
Iteration 18, loss = 1.57693969
Iteration 19, loss = 1.57436528
Iteration 20, loss = 1.57216023
Iteration 21, loss = 1.57006410
Iteration 22, loss = 1.56821340
Iteration 23, loss = 1.56601211
Iteration 24, loss = 1.56436734
Iteration 25, loss = 1.56253131
Iteration 26, loss = 1.56063826
Iteration 27, loss = 1.55910293
Iteration 28, loss = 1.55769432
Iteration 29, loss = 1.55599383
Iteration 30, loss = 1.55447783
Iteration 31, loss = 1.55310477
Iteration 32, los

MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(16, 32, 64, 32, 16, 8, 2),
       learning_rate='adaptive', learning_rate_init=0.001, max_iter=10000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [67]:
mlp.score(X_val, y_val)

0.25510204081632654

In [68]:
mlp.score(X_train, y_train)

0.26309067688378035

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [94]:
rfc = RandomForestClassifier(n_estimators=800, max_depth=25, max_features='log2', n_jobs=-1)

In [95]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=25, max_features='log2', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=800, n_jobs=-1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [96]:
rfc.score(X_val, y_val)

0.54846938775510201

In [97]:
rfc.score(X_train, y_train)

0.9323116219667944

In [76]:
rfc.feature_importances_

array([ 0.09562209,  0.09380033,  0.17785503,  0.11716764,  0.1602549 ,
        0.00320034,  0.02354381,  0.0049912 ,  0.02229671,  0.00837976,
        0.00604363,  0.01497333,  0.07683277,  0.02514093,  0.00018769,
        0.16970983])

In [77]:
from sklearn.ensemble import GradientBoostingClassifier

In [78]:
gboost = GradientBoostingClassifier(learning_rate=0.01, n_estimators=700, max_depth=32, max_features='log2', min_samples_split=4)

In [80]:
gboost.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=32,
              max_features='log2', max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=4, min_weight_fraction_leaf=0.0,
              n_estimators=700, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [82]:
gboost.score(X_train, y_train)

0.99744572158365263

In [83]:
gboost.score(X_val, y_val)

0.63775510204081631

In [86]:
gboost.feature_importances_

array([ 0.08882333,  0.08075878,  0.03556295,  0.07939071,  0.20276349,
        0.01530834,  0.05679428,  0.02783822,  0.1687047 ,  0.24405519])

In [84]:
from sklearn.tree import ExtraTreeClassifier

In [85]:
etc = ExtraTreeClassifier(max_depth=20)
etc.fit(X_train, y_train)
print(etc.score(X_train, y_train))
print(etc.score(X_val, y_val))


0.697318007663
0.579081632653


In [86]:
etc.feature_importances_

array([ 0.05635238,  0.06818842,  0.33420234,  0.17317662,  0.06510057,
        0.00389701,  0.0103187 ,  0.01213399,  0.03200929,  0.0113986 ,
        0.01344729,  0.02126289,  0.07952058,  0.02159589,  0.        ,
        0.09739542])

In [88]:
rfc.score(X_test, y_test)

0.5653061224489796

In [89]:
gboost.score(X_test, y_test)

0.5653061224489796

In [90]:
mlp.score(X_test, y_test)

0.19591836734693877

In [92]:
logistic_model.score(X_test, y_test)

0.52857142857142858